web:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3000:3000"
  links:
    - "db"

db:
  image: postgres
  environment:
    DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    SEQ_DB: postgres
    SEQ_USER: postgres
    SEQ_PW: postgres
  ports:
    - "5432:5432"
